--- #YAML:1.0
name:                Yahoo-BBAuth
version:             0.50
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Class::Accessor:               0
    JSON:                          0
    LWP:                           5.6
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Jiro Nishiguchi <jiro@cpan.org> Jason Levitt <jlevitt@yahoo-inc.com>
